//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsheringEntities : DbContext
    {
        private static CarsheringEntities _context;
        public CarsheringEntities()
            : base("name=CarsheringEntities")
        {
        }

        public static CarsheringEntities GetContext()
        {
            if (_context == null)
                _context = new CarsheringEntities();
            return _context;
        }

    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Registr> Registr { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
